### PR TITLE
OscarCI: add metadata toml and github workflow

### PR DESCRIPTION
**Pull request by benlorenz**
lets try this

### CODE REVIEW

**Comment by fieker** [comment]
On Thu, Mar 04, 2021 at 06:18:28AM -0800, Benjamin Lorenz wrote:
> lets try this
> You can view, comment on, or merge this pull request online at:

Merged - and now?

**Comment by benlorenz** [comment]
Tests are running, but the important ones failed to check out the correct repo because a small incomplete refactoring.

Can you please re-run the tests?

**Comment by fieker** [comment]
How?

**Comment by fieker** [comment]
On Thu, Mar 04, 2021 at 06:36:00AM -0800, Benjamin Lorenz wrote:
> Tests are running, but the important ones failed to check out the correct repo because a small incomplete refactoring.
> 
> Can you please re-run the tests?
> 
Tests are re-running

**Pull request merged**
